#' Read the TCPS data contained within an SPSS file generated by Ken Meadows and transform the data into a tidy format
#'
#' @param file full file path to the SPSS .sav file
#'
#' @return a tidy data frame of TCPS data
#' @export
tidy_tcps <- function(file){

 data <- haven::read_sav(file) %>%
    dplyr::mutate_if(haven::is.labelled, function(x) haven::as_factor(x, levels = "label")) %>%
    dplyr::mutate(survey = stringi::stri_extract_first_regex(basename(file), "Faculty|Staff|Students")) %>%
    dplyr::select(.data$survey, .data$PartNum, dplyr::contains("agree"), dplyr::contains("imp"), dplyr::matches("Q\\d+[ai]\\b")) %>%
    purrr::map_df(~replace(.x, is.nan(.x), NA))

  srvy <- rlang::quo(unique(data[["survey"]]))

  selection <- dplyr::filter(.faculty_levers, .data$survey == UQ(srvy))

  selection$data <- list(data)

  purrr::pmap_df(selection, scale_helper) %>%
    dplyr::rename(part_num = .data$PartNum) %>%
    dplyr::distinct(.data$part_num, .data$item, .data$type, .data$scale, .keep_all = TRUE) %>%
    dplyr::ungroup() %>%
    split(.$type) %>%
    purrr::map(~dplyr::select(.x, -.data$type) %>% tidyr::spread( item, value)) %>%
    purrr::reduce(dplyr::left_join, by = c("survey", "part_num", "scale")) %>%
    dplyr::select(.data$survey, .data$part_num, .data$scale, .data$assessteach, .data$brengage, .data$impteach, .data$infrastruct, .data$instinit, .data$teachrec, dplyr::pull(.questions,.data$question))

}
