tcps_read_excel <- function(file, ...) {

  data <- readxl::read_excel(file,col_names = FALSE) %>%
    janitor::clean_names()

  metadata <- tibble::tibble(variable = t(data[1,]),
                             description = t(data[2,]),
                             json = t(data[3,]))

  data <- data[-1:-3,]

  # Put in long format
  long_data <- purrr::set_names(data, metadata$variable) %>%
    janitor::clean_names() %>%
    dplyr::mutate(part_num = row_number(.data$status)) %>%
    tidyr::gather(question, value, dplyr::matches("q\\d+")) %>%
    dplyr::mutate(scale = dplyr::case_when(grepl("_1_\\d", .data$question, ignore.case = TRUE) ~ "agreement",
                                           grepl("_2_\\d", .data$question, ignore.case = TRUE) ~ "importance"),
                  item = as.numeric(stringr::str_extract(.data$question, "\\d$")),
                  block_start = readr::parse_number(stringr::str_extract(.data$question, "^q(\\d+)")),
                  block_end = readr::parse_number(stringr::str_extract(.data$question, "_q(\\d+)")),
                  q_number = .data$block_start + (.data$item - 1))

  # Summarize lever values
  levers <- long_data %>%
    dplyr::filter(!is.na(.data$scale)) %>%
    dplyr::group_by(.data$part_num, .data$block_start, .data$block_end, .data$scale) %>%
    dplyr::summarize(value = mean(as.numeric(value), na.rm = TRUE)) %>%
    dplyr::mutate(value = ifelse(is.nan(value), NA_real_, value),
                  value = as.character(value)) %>%
    dplyr::ungroup()

  # Get lever map
  lever_map <- levers %>%
    dplyr::distinct(.data$block_start, .data$block_end) %>%
    dplyr::mutate(lever = sprintf("lever%s", dplyr::row_number(.data$block_start)))

  # Join summarize levers to lever map
  full_levers <- levers %>%
    dplyr::left_join(lever_map, by = c("block_start", "block_end"))

  out <- long_data %>%
    dplyr::left_join(lever_map) %>%
    dplyr::mutate(question = if_else(is.na(lever), question, sprintf("%s_q%s", lever, item))) %>%
    dplyr::bind_rows(full_levers)


}



#' Read the TCPS data contained within an SPSS file generated by Ken Meadows and transform the data into a tidy format
#'
#' @param file full file path to the SPSS .sav file
#'
#' @return a tidy data frame of TCPS data
#' @export
tidy_tcps <- function(file) {

  data <- haven::read_spss(file) %>%
    dplyr::mutate_if(haven::is.labelled, function(x) haven::as_factor(x, levels = "values")) %>%
    dplyr::mutate_if(is.factor, as.character) %>%
    dplyr::mutate(survey = stringi::stri_extract_first_regex(basename(file), "Faculty|Staff|Student")) %>%
    dplyr::select(.data$survey, dplyr::contains("part", ignore.case = TRUE), dplyr::contains("lever", ignore.case = TRUE), dplyr::matches("Q\\d+_Q\\d+_\\d_\\d"), dplyr::matches("L\\d_[Ai]_Q\\d")) %>%
    dplyr::select(-dplyr::contains("PRIORITY")) %>%
    purrr::map_df(~replace(.x, is.nan(.x), NA)) %>%
    janitor::clean_names()

  data <- tidyr::gather(data, "item", "value", -.data$survey, -dplyr::contains("part", ignore.case = TRUE), convert = FALSE)

  srvy <- rlang::quo(unique(data[["survey"]]))


  data <- data %>%
    dplyr::mutate(scale = dplyr::case_when(grepl("a\\b", .data$item, ignore.case = TRUE) ~ "agreement",
                                           grepl("_a_", .data$item, ignore.case = TRUE) ~ "agreement",
                                           grepl("_i_", .data$item, ignore.case = TRUE) ~ "importance",
                                           grepl("i\\b", .data$item, ignore.case = TRUE) ~ "importance"),
                  item = ifelse(grepl("lever", .data$item, ignore.case = TRUE), stringi::stri_extract_first_regex(.data$item, "lever\\d"),  gsub("_[ai]_", "_", .data$item, ignore.case = TRUE)),
                  item = gsub("l(\\d)", "lever\\1", .data$item),
                  type = !!srvy) %>%
    dplyr::select(.data$survey, part_num = .data$participant, .data$scale, .data$item, .data$type, .data$value) %>%
    tidyr::spread("item", "value", drop = TRUE, convert = TRUE)

}

if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))
