#' Read the TCPS data contained within an SPSS file generated by Ken Meadows and transform the data into a tidy format
#'
#' @param file full file path to the SPSS .sav file
#'
#' @return a tidy data frame of TCPS data
#' @export
tidy_tcps <- function(file){

  data <- haven::read_spss(file) %>%
    dplyr::mutate_if(haven::is.labelled, function(x) haven::as_factor(x, levels = "values")) %>%
    dplyr::mutate_if(is.factor, as.character) %>%
    dplyr::mutate(survey = stringi::stri_extract_first_regex(basename(file), "Faculty|Staff|Student")) %>%
    dplyr::select(.data$survey, dplyr::contains("part", ignore.case = TRUE), dplyr::contains("lever", ignore.case = TRUE), dplyr::matches("Q\\d+_Q\\d+_\\d_\\d"), dplyr::matches("L\\d_[Ai]_Q\\d")) %>%
    dplyr::select(-dplyr::contains("PRIORITY")) %>%
    purrr::map_df(~replace(.x, is.nan(.x), NA)) %>%
    janitor::clean_names()

  data <- tidyr::gather(data, "item", "value", -.data$survey, -dplyr::contains("part", ignore.case = TRUE), convert = FALSE)

  srvy <- rlang::quo(unique(data[["survey"]]))


  data <- data %>%
    dplyr::mutate(scale = dplyr::case_when(grepl("a\\b", .data$item, ignore.case = TRUE) ~ "agreement",
                                           grepl("_a_", .data$item, ignore.case = TRUE) ~ "agreement",
                                           grepl("_i_", .data$item, ignore.case = TRUE) ~ "importance",
                                           grepl("i\\b", .data$item, ignore.case = TRUE) ~ "importance"),
                  item = ifelse(grepl("lever", .data$item, ignore.case = TRUE), stringi::stri_extract_first_regex(.data$item, "lever\\d"),  gsub("_[ai]_", "_", .data$item, ignore.case = TRUE)),
                  item = gsub("l(\\d)", "lever\\1", .data$item),
                  type = !!srvy) %>%
    dplyr::select(.data$survey, part_num = .data$participant, .data$scale, .data$item, .data$type, .data$value) %>%
    tidyr::spread("item", "value", drop = TRUE, convert = TRUE)

}

if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))
